providers = ["...", "node"]

[phases.setup]
nixPkgs = ["...", "python3", "python3Packages.pip"]

aptPkgs = [
  "tesseract-ocr",
  "tesseract-ocr-eng",
  "libgl1",
  "libglib2.0-0"
]

[phases.install]
cmds = [
  "npm install",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r server/scripts/requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]
